name: Run CI checks

on: [pull_request]

jobs:
  test-affected:
    runs-on: ubuntu-latest
    name: Test Affected
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npx run nx affected:test -- --base=origin/master --parallel
  build-affected:
    runs-on: ubuntu-latest
    name: Build Affected
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npx run nx affected:build -- --base=origin/master --parallel
  lint-affected:
    runs-on: ubuntu-latest
    name: Lint Affected
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npx run nx affected:lint -- --base=origin/master --parallel
  e2e-affected:
    runs-on: ubuntu-latest
    name: e2e Affected
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npx run nx affected:e2e -- --base=origin/master --parallel